Lachy-Dauth-30a91c0add83349131251a3d1788ececb3ebb718/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("new", views.new, name="new"),
    path("edit", views.edit, name="edit"),
    path("random", views.random_entry, name="random"),
    path("<str:name>", views.entry, name="new")
]

Lachy-Dauth-30a91c0add83349131251a3d1788ececb3ebb718/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls")),
]

Lachy-Dauth-30a91c0add83349131251a3d1788ececb3ebb718/encyclopedia/models.py
from django.db import models

# Create your models here.

Lachy-Dauth-30a91c0add83349131251a3d1788ececb3ebb718/encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms
from django.contrib import messages
import random

import markdown2

from . import util

class new_entry_form(forms.Form):
    title = forms.CharField(label="Title", max_length=100,
                            widget=forms.TextInput(
                            attrs={'class': "form-control"}))

    content = forms.CharField(label="Content",
                            widget=forms.Textarea(
                            attrs={'class': "form-control"}))

class new_content_form(forms.Form):
    content = forms.CharField(label="Content",
                            widget=forms.Textarea(
                            attrs={'class': "form-control"}))

def filter_list(string_list, target):
    filtered_list = []
    for string in string_list:
        if target.lower() in string.lower():
            filtered_list.append(string)
    return filtered_list

def index(request):
    if request.method == "POST":
        form = forms.Form(request.POST)
        return render(request, "encyclopedia/index.html", {
            "title": "Pages Including \"" + form.data["q"]+"\"",
            "entries": filter_list(util.list_entries(), form.data["q"])
        })
    else:
        return render(request, "encyclopedia/index.html", {
            "title": "All Pages",
            "entries": util.list_entries()
        })


def new(request):
    if request.method == "POST":
        form = new_entry_form(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            if util.get_entry(title):
                messages.info(request, 'This page already exists!')
                return render(request, "encyclopedia/new.html", {
                    "form": form
                })
            else:
                util.save_entry(title, form.cleaned_data["content"])
                return HttpResponseRedirect(reverse("wiki:index") + title)
        else:
            return render(request, "encyclopedia/new.html", {
                "form": form
            })
    else:
        return render(request, "encyclopedia/new.html", {
            "form": new_entry_form()
        })

def edit(request):
    if request.method == "POST":
        form = new_content_form(request.POST)
        if form.data["first"] == "True":
            return render(request, "encyclopedia/edit.html", {
                "title": form.data["title"],
                "form": form
            })
        else:
            if form.is_valid():
                title = form.data["title"]
                util.save_entry(title, form.cleaned_data["content"])
                return HttpResponseRedirect(reverse("wiki:index") + title)
            else:
                return render(request, "encyclopedia/edit.html", {
                    "title": form.data["title"],
                    "form": form
                })
    else:
        return render(request, "encyclopedia/new.html", {
            "form": new_content_form()
        })

def entry(request, name):
    page_content = util.get_entry(name)
    if page_content == None:
            return render(request, "encyclopedia/error.html", {
            "title": name
        })

    return render(request, "encyclopedia/entry.html", {
        "title" : name,
        "content" : markdown2.markdown(page_content),
        "raw_content": page_content
    })

def random_entry(request):
    return entry(request, random.choice(util.list_entries()))

Lachy-Dauth-30a91c0add83349131251a3d1788ececb3ebb718/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit {{ title }}
{% endblock %}

    {% block body %}
    <h1>Edit {{ title }}</h1>
    <form action="{% url 'wiki:edit' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="title" value="{{ title }}">
        <input type="hidden" name="first" value="False">
        {{ form }}
        <br>
        <input type="submit" class="btn btn-primary">
    </form>

{% endblock %}

Lachy-Dauth-30a91c0add83349131251a3d1788ececb3ebb718/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}

    {{ content|safe }}
    
    <br>

    <form action="{% url 'wiki:edit' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="first" value="True">
        <input type="hidden" name="title" value="{{title}}">
        <input type="hidden" name="content" value="{{raw_content}}">
        <input type="submit" value="Edit">
    </form>

{% endblock %}

Lachy-Dauth-30a91c0add83349131251a3d1788ececb3ebb718/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Page Doesn't Exist
{% endblock %}

{% block body %}
    <h1>Sorry, <i>{{ title }}</i> Doesn't Exist</h1>

    <br>
    
    <section>
        <p>If you would like to add this page please press the <strong>Create New Page</strong> button.</p>
        <br>
        <i>Thanks</i>
    </section>

{% endblock %}

Lachy-Dauth-30a91c0add83349131251a3d1788ececb3ebb718/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

Lachy-Dauth-30a91c0add83349131251a3d1788ececb3ebb718/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row" style="margin: 0;">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:index' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

Lachy-Dauth-30a91c0add83349131251a3d1788ececb3ebb718/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Entry
{% endblock %}

{% block body %}
    <h1>New Entry</h1>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="{% url 'wiki:new' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <br>
        <input type="submit" class="btn btn-primary">
    </form>

{% endblock %}